language: node_js
node_js:
  - "node"

cache: npm

script: build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: "gh-pages"
  on:
    branch: master
